#%RAML 1.0
title: Mule API 1-test
version: 1.0
mediaType: application/json
baseUri: http://localhost:8081

/demo:
  get:
    
    responses: 
      200:
        body: 
          application/json:
            example:  |
              {
                  "songId":1,
                  "songTitle":"tumbin"
              }                   
            
            
            
